KrabBlog27/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blogasek.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls"))
]

accounts/urls.py
from django.urls import  path
from . import views

urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup")
]

blogasek/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("detail/<int:pk>", views.DetailView.as_view(), name="detail"),
    path("detail/<int:pk>/comment/", views.CreateComment.as_view(), name="comment"),
    path("user/<int:pk>", views.UserView.as_view(), name="user"),
    path("create/", views.CreatePost.as_view(), name="create"),
]

accounts/models.py
from django.db import models

# Create your models here.

blogasek/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE,)
    text = models.CharField(max_length=8000)
    pub_date = models.DateTimeField("Date published")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("detail", args=[str(self.id)])


class Comment(models.Model):
    blog_post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)
    pub_date = models.DateTimeField("Date published")

    def __str__(self):
        return "{0} - {1}".format(self.author.nick, self.pub_date)

blogasek/forms.py
from django.forms import ModelForm
from . import models


class CommentForm(ModelForm):
    class Meta:
        model = models.Comment
        fields = ("text",)

accounts/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    template_name = "registration/signup.html"

    def get_success_url(self):
        return reverse_lazy("login")

blogasek/views.py
from django.shortcuts import redirect
import django.views.generic as generic
from django.utils import timezone
from .models import *
from . import forms


# Create your views here.
class IndexView(generic.ListView):
    model = BlogPost
    template_name = "blogasek/index.html"

    def get_queryset(self):
        return BlogPost.objects.order_by("pub_date")


class DetailView(generic.DetailView):
    model = BlogPost
    template_name = "blogasek/detail.html"


class UserView(generic.DetailView):
    model = User
    template_name = "blogasek/user.html"


class CreatePost(generic.CreateView):
    model = BlogPost
    fields = ["text", "title"]
    template_name = "blogasek/create_post.html"

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        post.pub_date = timezone.now()
        post.save()
        return redirect("detail", pk=post.pk)


class CreateComment(generic.CreateView):
    form_class = forms.CommentForm
    template_name = "blogasek/create_comment.html"

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.author = self.request.user
        comment.blog_post = BlogPost.objects.get(pk=self.kwargs["pk"])
        comment.pub_date = timezone.now()
        comment.save()
        return redirect("detail", pk=comment.blog_post.pk)


class UpdatePost(generic.UpdateView):
    model = BlogPost
    fields = ["text", "title"]

templates/blogasek/create_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add comment - {{ blogpost.title }}</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
</body>
</html>

templates/blogasek/create_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Post</title>
</head>
<body>
{% if perms.blogasek.add_blogpost %}
    <a href="{% url "index" %}">Go back</a>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Post">
    </form>
{% else %}
    You don't have permission to create blog posts <br><br>
    <a href="{% url "index" %}">Go back</a>
{% endif %}

</body>
</html>

templates/blogasek/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ blogpost.title }}</title>
</head>
<body>
    <div id="header">
        <a href="{% url "index" %}">Main Page</a>
        <br>
        <br>
    </div>

    <div id="main">
        {{ blogpost.title }}<br>
        {{ blogpost.author.username}} - {{ blogpost.pub_date }}<br><br>
        {{ blogpost.text }}<br>
        <br>
    </div>

    <a href="{% url "comment" pk=blogpost.id %}">Add comment</a>

    <div id="comments">
        {% for comment in blogpost.comment_set.all %}
        {{ comment.author.username }} - {{ comment.pub_date }}<br>
        {{ comment.text }}<br><br>
    {% endfor %}
    </div>

</body>
</html>

templates/blogasek/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
</head>
<body>

<div id="header">
    {% if user.is_authenticated %}
        <a href="{% url "create" %}">Create Post</a> - <a href="{% url "logout" %}"> Log out</a>
    {% else %}
        <a href="{% url "login" %}">Log in</a> - <a href="{% url "signup" %}">Sign up</a>
    {% endif %}
</div>

<div id="main">
    <p>
        {% for post in blogpost_list %}
            <a href="{% url "detail" post.id %}">{{ post.title }}</a><br>
            <strong>{{ post.author.username }}</strong> - {{ post.pub_date }}
            <br>
            <br>
            {{ post.text }}
            <br>
            <br>
            {% for comment in post.comment_set.all %}
                <strong>{{ comment.author.username }}</strong>
                <br>
                {{ comment.text }}
            {% endfor %}
        {% endfor %}
    </p>
</div>

</body>
</html>

templates/blogasek/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ user.username }}</title>
</head>
<body>
    <strong>{{ user.username }}</strong>

</body>
</html>